# Generated by Django 6.0.2 on 2026-03-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=11)),
                ('id_idoso', models.IntegerField(default=0, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField(default=0)),
                ('cpf', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=128)),
                ('token', models.CharField(max_length=250, unique=True)),
                ('paciente_ids', models.JSONField(default=list)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id_doctor', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=200)),
                ('cep', models.CharField(max_length=8)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('remedio', models.CharField(max_length=120)),
                ('horario', models.TimeField()),
                ('remedios', models.JSONField(default=list)),
                ('horarios', models.JSONField(default=list)),
                ('id_doctor', models.IntegerField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
